### PR TITLE
Bug fix on single band structure plot

### PR DESCRIPTION
**Pull request by Filo3dg**

### CODE REVIEW

**Comment by bcamino** [comment]
Hi @Filo3dg, thank you for this PR. Could you please upload the plot Jupyter notebook showing these new plotting functions are working properly? This way it will be easier to review the code. 

Cheers,

Bruno

**Comment by Filo3dg** [comment]
Hi @bcamino, 
I have added the example notebook for the plot.py collection, now we should be able to merge the code.

Cheers,

Filippo

**Comment by bcamino** [comment]
Hi @Filo3dg , thank you very much for this. I am going to review it asap. Cheers, Bruno

**Review by bcamino — APPROVED** [review]
Hi @Filo3dg , this is great. The plots in the Notebook look fantastic. I'll close and approve this PR. I was wondering if you would like to add a tutorial for example in tutorials/plot_tutorial.ipynb for the MSSC2022? Cheers, Bruno

**Comment by Filo3dg** [comment]
Hi @bcamino,
Yep I will create a tutorial notebook in the upcoming weeks

Cheers, Filippo

**Pull request merged**
